//! Phase 6-6b E2E: uint256_arith integration via bridge.
//!
//! Loads a fixture with uint256_arith + byte_check_rom entries
//! (generated by tests/zk-uint256.test.js) and proves it through the full
//! bridge path. The fixture extends a valid tree witness with uint256 entries
//! at num_lookups=0 (no PRED_BUS demand), testing that:
//! 1. Bridge correctly parses uint256_arith and byte_check_rom JSON fields
//! 2. ByteCheckRomAir and Uint256ArithChip are constructed and proved
//! 3. Arithmetic constraints (carry chain) are verified
//! 4. Byte range checks (BYTE_CHECK_BUS) balance correctly

use proof_checker::bridge::{prove_witness, WitnessJson};

fn load_fixture(name: &str) -> String {
    let path = format!(
        "{}/tests/fixtures/{}.json",
        env!("CARGO_MANIFEST_DIR"),
        name
    );
    std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("fixture {name}.json not found at {path}: {e}"))
}

#[test]
fn p6_uint256_e2e_bridge_integration() {
    let json = load_fixture("uint256_e2e");
    let witness: WitnessJson = serde_json::from_str(&json).expect("parse uint256_e2e fixture");

    // Verify fixture has uint256 entries
    assert!(!witness.uint256_arith.is_empty(), "fixture should have uint256_arith entries");
    assert_eq!(witness.uint256_arith[0].len(), 166, "uint256_arith row should be 166 cols (101 prep + 65 main)");
    assert_eq!(witness.byte_check_rom.len(), 256, "byte_check_rom should have 256 entries");

    // Prove through full bridge path
    prove_witness(&witness).expect("STARK verification should pass with uint256 entries");
    println!("  uint256 E2E: {} uint256_arith entries proved via bridge", witness.uint256_arith.len());
}

/// Test that the bridge handles empty uint256 sections gracefully.
#[test]
fn p6_uint256_e2e_empty_sections() {
    let json = load_fixture("custom_chip_inc");
    let witness: WitnessJson = serde_json::from_str(&json).expect("parse custom_chip_inc fixture");

    // Base fixture should not have uint256 entries
    assert!(witness.uint256_arith.is_empty(), "base fixture should have no uint256_arith");
    assert!(witness.byte_check_rom.is_empty(), "base fixture should have no byte_check_rom");

    // Should still prove fine (no uint256 chips added)
    prove_witness(&witness).expect("STARK verification should pass without uint256 entries");
}
