#!/usr/bin/env node

// const calc = require('../ll.json');
// const clc = require('cli-color');
// const helper = require('../lib/helper.js');
//
// const calcParser = require("../lib/parser.js");
const {parser, lexer} = require("../lib/llt_compiler.js");
const fs = require("fs");



// TODO - export to helper
const right = function (str) {
  return "-".repeat(process.stdout.columns - str.length - 4 ) + "  " + str
}


let args = process.argv.slice(2);
let llt_path = args[0];

let llt_program = fs.readFileSync(llt_path, {filetype: "utf8"}).toString();

lexer.setInput(llt_program);
lexer.begin()
let next;

console.log(right("LEXING")+"\n");

while(!lexer.done) {
  next = lexer.lex();
  let str = next === lexer.yytext ? next : next + " " + lexer.yytext;
  console.log(str);
}

console.log("\n"+right("RESULT")+"\n");

let ast = parser.parse(llt_program);

let rules_str = parser.yy.LLT.db.bwd
  .map(rule =>
    `bwd_def:\n`+rule
      .map(s => `  ${s}`)
      .join("\n"))
  .join('\n\n')
console.log(rules_str);

// console.log(ast);
