#!/usr/bin/env node

const calc = require('../ll.json');

const calcParser = require("../lib/parser.js");
const Parser = calcParser(calc);


let meta = calc.calc_structure_rules_meta.Contexts;
Object.keys(meta)
.forEach(ctxName => {
  let metactx = meta[ctxName];
  let ctx = calc.calc_structure_rules[ctxName];
  let rules = Object.keys(ctx)
  .map(ruleName => " - " + ctx[ruleName].ascii)
  .join("\n")

  console.log(`${ctxName} - ${metactx.label || ""}\n${rules}\n`);
})
