#!/usr/bin/env node

const calc = require('../ll.json');
const clc = require('cli-color');
const helper = require('../lib/helper.js');
const Calc = require("../lib/calc.js");

const calcParser = require("../lib/parser.js");
Calc.init(calc);
const Parser = calcParser();

const args = process.argv.slice(2);

const showIds = args.indexOf("--ids") > -1;
const showCode = args.indexOf("--code") > -1;


const calc_ = Parser.calc;

if(showIds) {
  Object.keys(Calc.db.rules).forEach(id => {
    let rule = Calc.db.rules[id];
    console.log(`${id}. ${rule.ctxName}.${rule.ruleName}`);
  })
  console.log(`\n`);
}


const bnf = Parser.grammar.bnf;

Object.keys(bnf).forEach(NTName => {
  let rules = bnf[NTName].map(rhs => rhs[0].trim() + (showCode && (1 in rhs) && (`\n     { ${rhs[1]} }`) || ""))
  console.log(`${NTName} :=\n  | ${rules.join("\n  | ")}\n`);
})
