#!/usr/bin/env node
// TODO - to get rid of shift-reduce conflicts for "e bin_op e" expressions, I cannot have non-terminal bin_op rules, therefore they should be propagated up to generate multiple "e '+' e" rules.

const DEBUG = !!process.env["DEBUG"];
const helper = require("../lib/helper.js");
const args = process.argv.slice(2);
let formulaStr = "(?Z, ?X), ?Y |- < AT? B , AT? C > : F?A xx F?B";
const formula = args && args[0] || formulaStr;

const calc = require('../ll.json');
const calcParser = require("../lib/parser.js");
const parser = calcParser(calc).parser;

let node = parser.parse(formula)

let tableargs = ["constr", "ascii", "formula"];


let latexTree = node.toTree("", true, tableargs)
console.log(helper.tree2dot(latexTree, tableargs));


// let latex_str = node.toString({style: "isabelle_se", brackets: true});

