#!/usr/bin/env node
// TODO - to get rid of shift-reduce conflicts for "e bin_op e" expressions, I cannot have non-terminal bin_op rules, therefore they should be propagated up to generate multiple "e '+' e" rules.

const ncp = require("copy-paste");

const DEBUG = !!process.env["DEBUG"];
const args = process.argv.slice(2);
const fs = require("fs");
const path = require("path");

const calc = require('../ll.json');
const calcParser = require("../lib/parser.js");
const parser = calcParser(calc).parser;

const parserCode = parser.generate({moduleMain: "{}"});
fs.writeFileSync(path.join(__dirname, "../out/parser.js"), parserCode)
fs.writeFileSync(path.join(__dirname, "../out/calc.json"), JSON.stringify(calc, false, 2))
