#!/usr/bin/env node
/**
 * Convert EVM hex bytecode to CALC `code PC V` facts.
 *
 * Usage:
 *   node tools/bytecode-to-ill.js <hex-string-or-file>
 *   node tools/bytecode-to-ill.js 0x6075565b...
 *   node tools/bytecode-to-ill.js path/to/contract.bin
 *
 * Output: CALC-compatible `code PC 0xHH *` lines to stdout
 */

const fs = require('fs');
const path = require('path');

// EVM opcode names for comments
const OPCODE_NAMES = {
  0x00: 'STOP', 0x01: 'ADD', 0x02: 'MUL', 0x03: 'SUB', 0x04: 'DIV',
  0x05: 'SDIV', 0x06: 'MOD', 0x07: 'SMOD', 0x08: 'ADDMOD', 0x09: 'MULMOD',
  0x0a: 'EXP', 0x0b: 'SIGNEXTEND',
  0x10: 'LT', 0x11: 'GT', 0x12: 'SLT', 0x13: 'SGT', 0x14: 'EQ',
  0x15: 'ISZERO', 0x16: 'AND', 0x17: 'OR', 0x18: 'XOR', 0x19: 'NOT',
  0x1a: 'BYTE', 0x1b: 'SHL', 0x1c: 'SHR', 0x1d: 'SAR',
  0x20: 'SHA3',
  0x30: 'ADDRESS', 0x31: 'BALANCE', 0x32: 'ORIGIN', 0x33: 'CALLER',
  0x34: 'CALLVALUE', 0x35: 'CALLDATALOAD', 0x36: 'CALLDATASIZE',
  0x37: 'CALLDATACOPY', 0x38: 'CODESIZE', 0x39: 'CODECOPY',
  0x3a: 'GASPRICE', 0x3b: 'EXTCODESIZE', 0x3c: 'EXTCODECOPY',
  0x3d: 'RETURNDATASIZE', 0x3e: 'RETURNDATACOPY', 0x3f: 'EXTCODEHASH',
  0x40: 'BLOCKHASH', 0x41: 'COINBASE', 0x42: 'TIMESTAMP', 0x43: 'NUMBER',
  0x44: 'DIFFICULTY', 0x45: 'GASLIMIT', 0x46: 'CHAINID', 0x47: 'SELFBALANCE',
  0x48: 'BASEFEE',
  0x50: 'POP', 0x51: 'MLOAD', 0x52: 'MSTORE', 0x53: 'MSTORE8',
  0x54: 'SLOAD', 0x55: 'SSTORE', 0x56: 'JUMP', 0x57: 'JUMPI',
  0x58: 'PC', 0x59: 'MSIZE', 0x5a: 'GAS', 0x5b: 'JUMPDEST',
  0x5f: 'PUSH0',
  0xf0: 'CREATE', 0xf1: 'CALL', 0xf2: 'CALLCODE', 0xf3: 'RETURN',
  0xf4: 'DELEGATECALL', 0xf5: 'CREATE2', 0xfa: 'STATICCALL',
  0xfd: 'REVERT', 0xfe: 'INVALID', 0xff: 'SELFDESTRUCT',
  0xa0: 'LOG0', 0xa1: 'LOG1', 0xa2: 'LOG2', 0xa3: 'LOG3', 0xa4: 'LOG4',
};
// DUP1-16, SWAP1-16, PUSH1-32
for (let i = 0; i < 16; i++) OPCODE_NAMES[0x80 + i] = `DUP${i + 1}`;
for (let i = 0; i < 16; i++) OPCODE_NAMES[0x90 + i] = `SWAP${i + 1}`;
for (let i = 1; i <= 32; i++) OPCODE_NAMES[0x5f + i] = `PUSH${i}`;

/**
 * How many immediate bytes a PUSH opcode consumes.
 * PUSHn (0x60..0x7f) pushes n bytes where n = opcode - 0x5f.
 * PUSH0 (0x5f) pushes zero (no immediate bytes).
 */
function pushSize(opcode) {
  if (opcode >= 0x60 && opcode <= 0x7f) return opcode - 0x5f;
  return 0;
}

// Parse input
const input = process.argv[2];
if (!input) {
  console.error('Usage: node tools/bytecode-to-ill.js <hex-string-or-file>');
  process.exit(1);
}

let hex;
if (fs.existsSync(input)) {
  hex = fs.readFileSync(input, 'utf8').trim();
} else {
  hex = input;
}
hex = hex.replace(/^0x/i, '');

if (!/^[0-9a-fA-F]*$/.test(hex) || hex.length % 2 !== 0) {
  console.error('Error: invalid hex input');
  process.exit(1);
}

const bytes = Buffer.from(hex, 'hex');

// For PUSHn with n > 1 byte, we treat the data as a single value at the first data PC.
// CALC convention: `code PC' V` where V is the full pushed value, PC' is first data byte.
// Then `!plus N PC' PC_Target` skips all N data bytes.

let pc = 0;
const lines = [];
while (pc < bytes.length) {
  const opcode = bytes[pc];
  const name = OPCODE_NAMES[opcode] || `0x${opcode.toString(16).padStart(2, '0')}`;
  const n = pushSize(opcode);

  // Pad PC for alignment
  const pcStr = String(pc).padStart(3, ' ');

  lines.push(`code ${pcStr}  0x${opcode.toString(16).padStart(2, '0')}  *   % ${name}`);

  if (n > 0) {
    // Extract the pushed value as a BigInt, convert to CALC hex
    const dataStart = pc + 1;
    const dataEnd = dataStart + n;
    if (dataEnd > bytes.length) {
      console.error(`Warning: PUSH${n} at PC ${pc} truncated (bytecode ends at ${bytes.length})`);
      break;
    }
    const valueBytes = bytes.slice(dataStart, dataEnd);
    const valueBigInt = BigInt('0x' + valueBytes.toString('hex'));

    // CALC convention: single `code PC' V` where V is the full value
    // For PUSH1: V is a single byte at PC+1
    // For PUSHn: V is the full n-byte value at PC+1
    const valueHex = '0x' + valueBigInt.toString(16).padStart(2, '0');
    const pcData = String(dataStart).padStart(3, ' ');
    lines.push(`code ${pcData}  ${valueHex}  *`);

    pc = dataEnd;
  } else {
    pc++;
  }
}

console.log('% Auto-generated by tools/bytecode-to-ill.js');
console.log(`% ${bytes.length} bytes total`);
console.log();
for (const line of lines) {
  console.log(line);
}
